#!/usr/bin/python2
from Xlib import X
from plwm import wmanager, keys, color, event
import panes, focus
import os

# Monkeypatch to jump to upper-left corner of window instead of center.
# Not worth subclassing or cloning imo.
def warp_patch(self, x = 0, y = 0):
	self._warppointer(x, y)
wmanager.Client._warppointer = wmanager.Client.warppointer
wmanager.Client.warppointer = warp_patch

# TODO: WM restart/exec? Ratpoison's tmpwm is neat too.
# TODO: Xinerama, EWMH, struts/reserved regions/fixed windows/nonfocusable windows?
# For struts, check out plwm.wmanager.Screen.alloc_border.

class keybindings(keys.KeyHandler):
	# TODO: Do this right. (config file)
	# We could do this like tritium does (config file has keybinding class)
	# or do some metaclass dickery to make it nicer for the user.
	# Or we could rewrite KeyHandler if we're feeling adventurous.
	def _spawn(self, command):
		self.wm.current_screen.system(command)
	def _spawn_term(self):
		self._spawn('urxvt')
		
	def M_S_Return(self, event):
		self._spawn_term()
	def M_p(self, event):
		self._spawn('dmenu_run')

	def M_h(self, event):
		self.wm.move_focus('left')
	def M_j(self, event):
		self.wm.move_focus('down')
	def M_k(self, event):
		self.wm.move_focus('up')
	def M_l(self, event):
		self.wm.move_focus('right')

	def M_S_comma(self, event):
		self.wm.current_screen.current_pane.vertical_split()
		self._spawn_term()
	def M_S_period(self, event):
		self.wm.current_screen.current_pane.horizontal_split()
		self._spawn_term()

	def M_1(self, event):
		self.wm.current_screen.current_pane.switch_window(0)
	def M_2(self, event):
		self.wm.current_screen.current_pane.switch_window(1)
	def M_3(self, event):
		self.wm.current_screen.current_pane.switch_window(2)
	def M_4(self, event):
		self.wm.current_screen.current_pane.switch_window(3)
	def M_5(self, event):
		self.wm.current_screen.current_pane.switch_window(4)


class wmclient(wmanager.Client, panes.panesClient):
	pass

class wmscreen(wmanager.Screen, color.Color, panes.panesScreen):
	pass

class wm(wmanager.WindowManager, focus.MoveFocus):
	client_class = wmclient
	screen_class = wmscreen
	def __wm_init__(self):
		keybindings(self)
		# This Dispatcher business is overengineering at its fucking finest.
		# Might as well use it since it's already there, though...
		# Anytime I think of hierarchical event dispatchers or asynchronous
		# message queues my mind is filled with images of fresh college grads
		# quivering with delight over web 3.0 and building scalable "apps" with
		# Clojure. Or perhaps I've been listening to Ted Dziuba for too long.
		# (google.com/search?q=taco+bell+programming, highly recommended.)
		self.misc_dispatch = event.Dispatcher(None)
		self.outline_pane = panes.OutlinePane(self)

wmanager.main(wm)

